-- Creating tables for Insurance Data
CREATE TABLE us_states(
     type VARCHAR(40),
     state VARCHAR(8) NOT NULL,
     state_name VARCHAR(40) NOT NULL,
     capital VARCHAR(40),
     population2015 INT,
     population2019 INT,
     area FLOAT,
     PRIMARY KEY (state),
     UNIQUE (state_name)
);
CREATE TABLE insurance_claims (     
     months_as_customer INT,
     age FLOAT,
     policy_number VARCHAR(20) NOT NULL,
     policy_bind_date DATE,
     policy_state VARCHAR(8) NOT NULL,
     policy_csl VARCHAR(20),
     policy_deductible FLOAT,
     policy_annual_premium FLOAT,
     umbrella_limit FLOAT,
     insured_zip INT,
     insured_sex VARCHAR(8),
     insured_education_level VARCHAR(20),
     insured_occupation VARCHAR(20),
     insured_hobbies VARCHAR(40),
     insured_relationship VARCHAR(40),
     capital_gains FLOAT,
     capital_loss FLOAT,
     incident_date DATE,
     incident_type VARCHAR(40),
     collision_type VARCHAR(40),
     incident_severity VARCHAR(40),
     authorities_contacted VARCHAR(40),
     incident_state VARCHAR(8),
     incident_city VARCHAR(40),
     incident_location VARCHAR(40),
     incident_hour_of_the_day INT,
     number_of_vehicles_involved INT,
     property_damage VARCHAR(8),
     bodily_injuries FLOAT,
     witnesses INT,
     police_report_available VARCHAR(8),
     total_claim_amount FLOAT,
     injury_claim FLOAT,
     property_claim FLOAT,
     vehicle_claim FLOAT,
     auto_make VARCHAR (20),
     auto_model VARCHAR(20),
     auto_year INT,
     fraud_reported VARCHAR(4),
     _c39 VARCHAR(8),
     PRIMARY KEY (policy_number),
     FOREIGN KEY (policy_state) REFERENCES us_states(state)
);

-- Trim spaces from state column
UPDATE us_states SET state = TRIM(state);
